const mysql = require('mysql2/promise');
const pool = mysql.createPool(process.env.JAWSDB_MARIA_URL);

module.exports = pool;

/*
DELIMITER $$
DROP FUNCTION IF EXISTS get_seq$$
CREATE FUNCTION get_seq (p_group_id INT UNSIGNED, p_seq_name VARCHAR(32))
 RETURNS INT UNSIGNED READS SQL DATA
BEGIN
 DECLARE RESULT_ID INT UNSIGNED;
 UPDATE master_seq SET id = LAST_INSERT_ID(id+1)
 WHERE group_id=p_group_id AND seq_name = p_seq_name;
 SET RESULT_ID = (SELECT LAST_INSERT_ID());
 RETURN RESULT_ID;
END $$
DELIMITER ;


DELIMITER $$
DROP FUNCTION IF EXISTS get_state$$
CREATE FUNCTION get_state(DOCUMENT_STATE INT UNSIGNED )
RETURNS VARCHAR(32)
BEGIN
  RETURN (CASE DOCUMENT_STATE
  WHEN 0 THEN "PENDING_ADDS"
  WHEN 1 THEN "PENDING_UPDATES"
  WHEN 2 THEN "ADDED"
  WHEN 3 THEN "UPDATED"
  WHEN 4 THEN "PREDEFINED"
  ELSE "UNKNOWN_STATE"
  END) ;
END $$
DELIMITER ;
*/
